---
driver:
  name: dokken
  privileged: false
  chef_version: 15.4.45

transport:
  name: dokken

provisioner:
  name: dokken
  client_rb:
    chef_license: "accept-silent"

platforms:
- name: debian
  driver_config:
    image: debian:10
    intermediate_instructions:
      - RUN /usr/bin/apt-get update &&
        /usr/bin/apt-get install apt-transport-https net-tools curl openssl --yes --no-install-recommends

verifier:
  name: inspec
  root_path: '/opt/verifier'
  sudo: false

suites:
  - name: create
    run_list:
      - recipe[glare_test::create]
    attributes:
      glare:
        email: <%= ENV['CF_EMAIL'] %>
        auth_key: <%= ENV['CF_AUTH_KEY'] %>
  - name: delete
    run_list:
      - recipe[glare_test::create]
      - recipe[glare_test::delete]
    attributes:
      glare:
        email: <%= ENV['CF_EMAIL'] %>
        auth_key: <%= ENV['CF_AUTH_KEY'] %>
