sudo: required
dist: trusty
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
install: echo "skip bundle install"
services: docker
env:
  matrix:
    - INSTANCE=create-debian
    - INSTANCE=delete-debian
  global:
    - secure: n4MaHS184i4t/Mz9dQ7x5dVq5p6bg+G/aAVMrCk4VZpb7oKuY0cYA6Lt8NakG2iXNEFbj1D2bUw3HtGC/er/IF/bkwTO5eLciH3feAN46MIgyGTJ3MmE6dcJVV5oJZLVxJbkDhCkp5V3D+1fhMKLa7u/V535uc1XAOVzs4Ymd2mSNagvHiOv7CqTpLH/ThMHWn95IsYChIoUcXnHL5SBmG2XU/g2Sje2AR2UmzjaYr0Hmk0cL+oYJvIKspIN0xdqPUIWvYgz+msELTbUn9SsFKswC7AQVBGdalbI6MigEG0SIYMSfMNtHJVhUB5DUFA5aIWmbmwddy4UkA1OcD8//yV3Z9lH7Hj2iSA8jXSloO5zB+ov64sqZK0MexEp/BOPpu1LpnWmFeLdkVxZiD/FcdhqaIaZtNj+lAU89DReVihYCfQ7pblcATGN7k3zEGqIGXd0m8WhqxSwZAGVhe6+ujwqTiaFmP1I6XENW8zFFfzjY6Rjvst1IkqHkNQ8HEHMdbDg2v7uliqe87u9KMoXl53daeoxLtxLHcu6G2lwX0t/gP3c3wX9IEX+MPG568iG6UDzrVR+RGN87gG1g7yx5/mlBiWpnfSp5NWWGSebvP8uZCBgb6DL4o2EcmIM7Sywu3DCXULkOZSTH3+dYUEmJCDH0mBvvfN5Gi/0RTafhnQ=
    - secure: sTBw+vB6IfrVIX+rEe2DrczPluhmte7ZWS1ur62I29KAMHJ/XKQaHQ/GUH7Kz8xVEkuKVWN4PcPDb14jM4Y5CYoTlEBz8rEJ6P0QPIQSfgPsxg4S86MGI+HKZU2Y2tD2gE9X7OzSDGPch6kooZmkWLDu1gwFh++Nj8ZoY5hVIXweG4DUi41VN5s4Z1D707v2NqQ1jIXagEOm9onkEKDlBuSZpxHUnod6K0ZQdbpJz9YcNkJkpE4tOPlakIAB9Gq7dp1XYneu0inEQ15/Bg3h8GC1Uojxp7bDfgJ/GvFH2mlUiq9DM+MlFoSu7WNo/C3ocRwdOooo5NUcSkYcvsXcjfvKVS9qYpRbH3mKHZsP+lkmK+DgmuBh/msPqLv0ZXdsddG3Vt7sO542oC7kq2jXp/fkyUnQ+dNG9byVtCJAYd85kEDCjvgo9VwQxjdx9hIjaueQyM6vyUwYpeDWRkt92ARmui+/SfQG2EpEziMtJuwZq+o3Ux7FXVsYG/Udqq9eID+6GHivLXSlmkjdFVv4zm/IcP78WLfAiqQiF9n8HA3WJF+6KPZDcJo9hQDZ604tDXnJcpda9Le9G4XSOgb2cuUT01U7MbznTlbI/n5fWjBpUJlBlTV2eXAIuoAX0hJPXOygpy4TWh7HfqGIii43F6peooDKJMBdyXYL+r58PP8=
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken glare
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
script:
  - 'if [ "$TRAVIS_REPO_SLUG" = "peertransfer/glare-cookbook" ]; then KITCHEN_LOCAL_YAML=.kitchen.yml kitchen verify ${INSTANCE}; fi'
after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
matrix:
  include:
    - script: "/opt/chefdk/embedded/bin/cookstyle"
      env: COOKSTYLE=1
    - script: "/opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -P"
      env: FOODCRITIC=1
    - script: "/opt/chefdk/embedded/bin/rspec"
      env: CHEFSPEC=1
